server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
        - name: CountFilter
      routes:
        - id: productRoute
          uri: lb://dh-fintech-product-service # URL a donde se hará redirect según predicado definido
          predicates: # reglas de análisis de request
            - Path=/products/**
        - id: userRoute
          uri: lb://dh-fintech-user-service
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header # Filtros que ya existen, con un clave y un nombre particular
            - AddResponseHeader=user-respons-header, custom-user-response-header